@startuml Update Shop (PUT :id)

header Massage Reservation Sequence Diagram : PUT SHOP
footer CEDT Chulalongkorn University
title "Update Shop"

participant "Client" as client
participant "<<router>>\n:shops" as router
participant "<<middleware>>\n:protect" as protect
participant "<<middleware>>\n:authorize" as authorize
participant "<<controllers>>\n:shops" as controller
participant "<<model>>\n:Shop" as model

client->router ++: PUT /shops/:id
router->protect ++: authenticate()
protect-->router --: User Validated
router->authorize ++: checkRole('admin')
authorize-->router --: Authorized
router->controller ++: updateShop()
controller->model ++: findByIdAndUpdate()

model->db ++: save()
db --> model --: success

model --> controller --: updatedReservation
controller --> client --: 200 OK (Updated)
@enduml